### ISSUE TITLE
Checkbox checked when checked: nil

### ISSUE THREAD

**Issue by robacarp** [amberframework/jasper-helpers#16]
This behavior was unexpected:

```slang
    == check_box name: "checkbox", checked: nil
```

renders this:
```html
    <input type="hidden" name="ping_check" id="ping_check" value="0"/>
    <input type="checkbox" name="ping_check" id="ping_check" value="1" checked=""/>
```

I believe that an input control with a `type="checkbox"` and a `checked` attribute, regardless of the _value_ of it renders the checkbox checked.

**Comment by elorest** [comment]
Use ` == check_box name: "checkbox", checked: false` as nil will just render an empty string.

**Comment by elorest** [comment]
@robacarp should be good now. Thanks.

**Comment by robacarp** [comment]
@elorest thank you patching this!
