### ISSUE TITLE
Labels for checkboxes are overlapping

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/jasper-helpers#21]
Currently checkbox labels have an accessibility issue:

![screenshot_20180101_125738](https://user-images.githubusercontent.com/3067335/34469741-5a2c4c3e-eef3-11e7-9384-8d53780f66e6.png)

@robacarp tried to fix it on #19 but that PR didn't solve this issue.

Looks like this is a bootstrap 3 issue, see [here](https://stackoverflow.com/questions/28745605/checkbox-label-overlapping-the-checkbox-bootstrap3)

**Comment by robacarp** [comment]
This can be closed now

**Comment by faustinoaq** [comment]
> This can be closed now

Why? 😅 

Please see: https://github.com/amberframework/jasper-helpers/pull/22 and https://github.com/amberframework/amber/pull/473

**Comment by robacarp** [comment]
@faustinoaq I have no idea, I was certain that the pull had been merged! Sorry for the chatter :[
