### ISSUE TITLE
Can't use form block with ECR

### ISSUE THREAD

**Issue by jcs** [amberframework/jasper-helpers#42]
With an ECR template such as:

```
<% form action: "/logout", method: :post do %>
  <%= submit "logout" %>
<% end %>
```

The content inside the `form` block is rendered properly, but the `<form>` tag is not rendered.  Trying to change it to `<%=` fails to parse:

```
 24 | <%= form action: "/logout", method: :post do %>
                                                   ^
Error: unexpected token: )
```

**Comment by elorest** [comment]
I noted this back in 2017 but it's a problem with ecr not amber. Because I use slim in ruby and slang in crystal I haven't pushed too hard to fix this. Could submit it as a bug to crystal though?

**Comment by jcs** [comment]
Apparently Ruby's ERB [works this same way](https://stackoverflow.com/questions/17374274/why-is-this-an-error-with-erb) so maybe this isn't a bug in ECR.  Rails does [something weird](https://github.com/rails/rails/blob/v4.1.8/actionview/lib/action_view/template/handlers/erb.rb#L38-L47) to support `<%= form_tag ... do %>` so maybe something custom is needed here too.
